import mongoose, {Document, Schema} from 'mongoose';
import {Profile as PassportProfile} from 'passport';

// Type interface representing a User document generated from the model we define below.
// Timestamp properties are generated by Mongo, but we have to indicate that manually here.
export interface IUser extends Document {    
    displayName: string,

    name: {
        familyName: string,
        givenName: string
    },

    provider: string,

    photos: {value: string} [],

    emails: {value: string} [],

    messages: string [],

    createdAt: string,

    updatedAt: string
}

const userSchema = new mongoose.Schema({
    displayName: {
        type: String,
        required: true,
        lowercase: true
    },

    name: {
        familyName: {
            type: String,
            lowercase: true
        },
        givenName: {
            type: String,
            lowercase: true
        },
    },

    provider: {
        type: String
    },

    photos: [{value: String}],

    emails: [{
        value: {
            type: String,
            required: true
        }
    }],

    messages: [{
        type: Schema.Types.ObjectId,
        required: true
    }]
}, {
    timestamps: true
});

const User = mongoose.model<IUser>('User', userSchema);

export default User;